#!/bin/bash

echo Installing gmigrate...

echo making symbolic link
ln -sf $(pwd)/gmigrate /usr/local/bin/gmigrate

echo adding bash completion in your ~/.bash_profile
sed -i '' "/gmigrate_bash_completion.bash/d" ~/.bash_profile
echo "source $(pwd)/gmigrate_bash_completion.bash" >> ~/.bash_profile

echo done
