#!/bin/bash

RED='\033[0;31m'
GRN='\033[1;32m'
WRN='\033[1;33m'
CLR='\033[0m'

# pass title, val, then expected
test () {
  title=$1
  val=$2
  expected=$3

  if [ "$val" == "$expected" ]; then
    printf "${GRN}PASSED: ${title}${CLR}\n"
  else
    printf "${RED}FAILED: ${title}${CLR}\n"
    printf "${WRN}Received: ${CLR}"
    printf "${RED}${val}${CLR}\n"
    printf "${WRN}Expected: ${CLR}"
    printf "${expected}"
    echo
  fi
}

# setup
rm -rf ../test_project
mkdir ../test_project
mkdir ../test_project/migrations
cd ../test_project
git init
clear

# test init
echo Testing init
test "should init folder" "$(gmigrate init)" "Initializing folder..."
test "shouldn't rerun init" "$(gmigrate init)" ".gmigrate exists. This project is already initialized."
test "should create default .gmigrate config file" "$(cat .gmigrate)" $'migrations=migrations\ngschemas=gschemas'
test "should create gschemas folder" "$(ls | grep gschemas)" "gschemas"

# test usage
test "should show usage by default" "$(gmigrate)" $'Usage:\n  gmigrate init|run\n  gmigrate add <schema> [procedure]'

# add initial commit
git add -A > /dev/null
git commit -m "initial commit" > /dev/null

# test add command
test "should add a schema folder" "$(gmigrate add private)" "Adding schema \"private\"..."
test "new schema folder should exist" "$(ls gschemas)" "private"
test "new schema folder should contain up, down, and procdures" "$(ls gschemas/private)" $'down.sql\nprocedures\nup.sql'
test "should add a new procedure" "$(gmigrate add private doTheThing)" 'Adding procedure "doTheThing" to schema "private"...'
test "procedure should have default sql if empty" "$(cat gschemas/private/procedures/doTheThing.sql)" $'CREATE OR REPLACE FUNCTION %schema%.%proc%() RETURNS void AS $$\nBEGIN\n  -- logic\nEND;\n$$ LANGUAGE plpgsql;'
test "should fail if schema does not exist" "$(gmigrate add public doTheThing)" "Schema public does not exist."

# test run command
test "shoud run the gmigrate run command" "$(gmigrate run)" "Generating migration files..."
test "should generate up and down migrations" "$(ls -1 migrations/ | wc -l | xargs)" "2"

# clean up
echo
cd ..
